### ISSUE TITLE
Dusha. Podcast .WAVs archive

### ISSUE THREAD

**Issue by vladsaveliev74** [salute-developers/golos#1]
Hi!

Downloading podcasts only by title and RSS links can be a daunting task. I think anyone who will work with the dataset will face this problem. I downloaded all the podcasts, cut them into samples as described in `podcast_metadata.tsv`

Attached is the link to the archive: [podcast_wavs.tar.gz (8,03 GB)](https://drive.google.com/file/d/1OxIwOoJHXrn1c-NdJhVS-0OsyG1kMwFf/view?usp=share_link)
md5sum: `31283c7747c30685eddb451690a4cc73`

**Comment by kondrat1997** [comment]
Hi!

Thank you very much! It will be very useful for all researchers
