### ISSUE TITLE
```504 Gateway Time-out``` when trying to download KenLM binary file or anything else.

### ISSUE THREAD

**Issue by mdvdv** [salute-developers/golos#4]
Hello. Link to KenLM binary file is not valid. I get ```504 Gateway Time-out```. How else can I access the files? Thanks for the answer.

**Comment by plastunkaterina** [comment]
Hello. Same problem with dataset files and quartznet15x15. Maybe there is a way to fix links?

**Comment by mdvdv** [comment]
> Hello. Same problem with dataset files and quartznet15x15. Maybe there is a way to fix links?

You may download the model and other files [here](https://www.openslr.org/114/) in the Mirrors sections. Let's hope their versions match this one.

**Comment by under-pressure88** [comment]
thanks for corrupted links and nobody cares still...

**Comment by mdvdv** [comment]
> sc links don't work at all

Yes, that's a pity, the link above might help

**Comment by mdvdv** [comment]
The links are working again, woohoo!
