### ISSUE TITLE
End-user voice recognition example

### ISSUE THREAD

**Issue by ioctl-user** [salute-developers/golos#6]
Hello!

Could you, please, add step by step example of the audiofile voice recognition for end-users?

**Comment by karpnv** [comment]
did you try this? 
https://github.com/salute-developers/golos/tree/master/golos/examples

**Comment by ioctl-user** [comment]
I have read README and there is no commands that get arbitrary audio file as input.

**Comment by karpnv** [comment]
You might want to read NeMo tutorial about it: https://github.com/NVIDIA/NeMo/blob/main/tutorials/asr/ASR_with_NeMo.ipynb
