### ISSUE TITLE
Pretrained checkpoints for Dusha emotion recognition dataset

### ISSUE THREAD

**Issue by vadimkantorov** [salute-developers/golos#7]
Hi!

Huge thanks for open-sourcing the Dusha emotion recognition dataset, the paper and baselines repro codebase.

By chance, could you provide the pretrained checkpoints obtained by those baselines experiment scripts?

Thanks!

**Comment by kondrat1997** [comment]
Hi!

We plan to release it and add some extra materials. Stay tuned :)

**Comment by vadimkantorov** [comment]
thanks a bunch!
